### ISSUE TITLE
Could not find artifact com.cooldatasoft:wicket-menu-parent:pom:6.12.0

### ISSUE THREAD

**Issue by lucrus73** [cooldatasoft/wicket-menu#2]
Central maven repository update required for 6.12.0. 

While trying to understand what's going on, I noticed I'm using wicket-menu 6.9.1 and maven central has 6.12.0. However after updating my pom.xml from

```
<dependency>
  <groupId>com.cooldatasoft</groupId>
  <artifactId>wicket-menu</artifactId>
  <version>6.9.1</version>
</dependency>
```

```
<repository>
  <id>wicket-menu-release</id>
  <url>http://wicket-menu.googlecode.com/svn/maven/repo</url>
</repository>
<repository>
  <id>wicket-menu-snapshot</id>
  <url>http://wicket-menu.googlecode.com/svn/maven/snapshot-repo</url>
</repository>
```

to

```
<dependency>
  <groupId>com.cooldatasoft</groupId>
  <artifactId>wicket-menu</artifactId>
  <version>6.12.0</version>
</dependency>
```

in order to get the latest version from maven central, I get the following error from mvn:

```
org.sonatype.aether.transfer.ArtifactNotFoundException: Could not find artifact com.cooldatasoft:wicket-menu-parent:pom:6.12.0 in Apache Nexus 
```

How should I edit my pom.xml in order to use the latest available wicket-menu version?

**Comment by cooldatasoft** [comment]
I have fixed the problem and released the artifacts into the central maven repo. It should become available in a couple of hours.

Since you are using 6.9.1 of wicket , you should use 6.9.1.1 version of wicket-menu

see [readme](https://github.com/cooldatasoft/wicket-menu/blob/master/README.md)  for details
