### ISSUE TITLE
Submenu items not showing up

### ISSUE THREAD

**Issue by lucrus73** [cooldatasoft/wicket-menu#3]
I expect the following code to show a "Options" menu with a "Test item" submenu item. It only shows "Options". Maybe it's my fault, but I can't find it.

```
MenuItem options = new MenuItem("Options");
options.getSubMenuItemList().add(new MenuItem("Test item", new AjaxFallbackLink<Void>("menuLink")
{
  @Override
  public void onClick(AjaxRequestTarget target)
  {
  }
}));

List<MenuItem> mainMenu = new ArrayList<>();
mainMenu.add(options);

add(new MultiLevelCssMenu("mainMenuBar", mainMenu));
```

I don't know how to attach a quickstart to this issue, so you can [download the quickstart here](http://www.sulweb.org/download/sparsi/issue3.zip).

**Comment by fmucar** [comment]
This actually does work but browsers cannot handle the html output with some wicket tags.

For this menu to work properly, you need to set the wicket not to output wicket tags. You can  do that application level or page level.

eg. getMarkupSettings().setStripWicketTags(true);

https://cwiki.apache.org/confluence/display/WICKET/How+to+remove+wicket+markup+from+output
